# Generated by Django 5.2.5 on 2025-08-25 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('isbn', models.CharField(blank=True, max_length=13, verbose_name='ISBN')),
                ('publication_year', models.IntegerField(blank=True, null=True, verbose_name='Año de Publicación')),
                ('synopsis', models.TextField(verbose_name='Sinopsis')),
                ('cover_image', models.URLField(blank=True, verbose_name='URL de Portada')),
                ('reading_status', models.CharField(choices=[('current', 'Lectura Actual'), ('upcoming', 'Próxima Lectura'), ('completed', 'Completado')], default='upcoming', max_length=20, verbose_name='Estado de Lectura')),
                ('reading_start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('reading_end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Calificación Promedio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Libros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('suggested_by_name', models.CharField(max_length=100, verbose_name='Sugerido por')),
                ('suggested_by_email', models.EmailField(max_length=254, verbose_name='Email del Sugerente')),
                ('reason', models.TextField(verbose_name='Razón de la Sugerencia')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sugerencia de Libro',
                'verbose_name_plural': 'Sugerencias de Libros',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Nombre')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Suscriptor Newsletter',
                'verbose_name_plural': 'Suscriptores Newsletter',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author_name', models.CharField(max_length=100, verbose_name='Autor')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('featured_quote', models.TextField(blank=True, verbose_name='Cita Destacada')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publicado')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.book', verbose_name='Libro Relacionado')),
            ],
            options={
                'verbose_name': 'Entrada de Blog',
                'verbose_name_plural': 'Entradas de Blog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Nombre del Autor')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Calificación')),
                ('review_text', models.TextField(verbose_name='Reseña')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.book')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('event_type', models.CharField(choices=[('meeting', 'Reunión del Club'), ('discussion', 'Discusión de Libro'), ('author_talk', 'Charla con Autor'), ('workshop', 'Taller'), ('other', 'Otro')], default='meeting', max_length=20, verbose_name='Tipo de Evento')),
                ('date', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
                ('online_link', models.URLField(blank=True, verbose_name='Enlace Online')),
                ('max_participants', models.IntegerField(blank=True, null=True, verbose_name='Máximo de Participantes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.book', verbose_name='Libro Relacionado')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image_url', models.URLField(verbose_name='URL de Imagen')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.event', verbose_name='Evento Relacionado')),
            ],
            options={
                'verbose_name': 'Imagen de Galería',
                'verbose_name_plural': 'Galería',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, to='main.genre', verbose_name='Géneros'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('profile_image', models.URLField(blank=True, verbose_name='Foto de Perfil')),
                ('favorite_genres', models.ManyToManyField(blank=True, to='main.genre', verbose_name='Géneros Favoritos')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
                'ordering': ['name'],
            },
        ),
    ]
